### ISSUE TITLE
"quickstart_db_user" does not exist

### ISSUE THREAD

**Issue by alessandrolomanto** [entando-k8s/entando-helm-quickstart#18]
Pod: quickstart-db-deployment-xxxxxx

```
  Normal   Pulled     9m30s (x5 over 11m)  kubelet, wrk2-oc   Successfully pulled image "docker.io/centos/postgresql-96-centos7:latest"
  Normal   Created    9m30s (x5 over 11m)  kubelet, wrk2-oc   Created container
  Warning  BackOff    85s (x42 over 11m)   kubelet, wrk2-oc   Back-off restarting failed container
```

```pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
.... done
server started
/var/run/postgresql:5432 - accepting connections
=> sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
ERROR:  role "quickstart_db_user" does not exist
```
This error appears only in the production cluster, locally with minishift I had no problems.
What could be the problem?

PS: quickstart-kc-db-deployment-xxxx Works!

**Comment by joewhite101** [comment]
Hey @alessandrolomanto I was just taking a look at this. Were you able to resolve your issue? We haven't seen that particular error before. Would be interested to know what you found. Also, feel free to start a discussion at forum.entando.org if you need more details

**Comment by alessandrolomanto** [comment]
Hi @joewhite101 , the problem was that I used the same folder for the 3 persistent volumes (my bad, sorry) and therefore the error was given by the fact that it tried to look for the user in the same folder where the other db was. I created 3 different dirs for the 3 pv and it works!

**Comment by joewhite101** [comment]
@alessandrolomanto Cool thanks. If you run into anything else let us know.
